apiVersion: v1
kind: Template
metadata:
  name: subscription-template
objects:
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    name: elasticsearch-operator
    namespace: openshift-operators-redhat
  spec:
    channel: "4.2"
    installPlanApproval: Automatic
    name: elasticsearch-operator
    source: ${SOURCE}
    sourceNamespace: openshift-marketplace
parameters:
  - name: SOURCE
