apiVersion: v1
kind: Template
metadata:
  name: generatejsonlog-template
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: log4j2
    labels:
      name: log4j2
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        name: log4j2
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          capabilities: Seamless Upgrades
          containerImage: quay.io/qiaolingtang/generate-log@sha256:0a6f1c44c3a16abb2485a67dc344051ae7d74bc4949f8dfa1d4ee62967d7cc57
          support: Qiaoling Tang
        creationTimestamp: null
        labels:
          name: log4j2
      spec:
        containers:
        - args:
          - /run.sh
          command:
          - /bin/sh
          image: quay.io/qiaolingtang/generate-log@sha256:0a6f1c44c3a16abb2485a67dc344051ae7d74bc4949f8dfa1d4ee62967d7cc57
          imagePullPolicy: IfNotPresent
          name: log4j2
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/generate-log
            name: config
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            name: generate-log
          name: config
- apiVersion: v1
  data:
    json.example: '{"message": "MERGE_JSON_LOG=true", "testcase": "logging-test", "level": "debug"," Layer1": "layer1 0", "layer2": {"name":"Layer2 1", "tips":"decide by PRESERVE_JSON_LOG"}, "StringNumber":"10", "Number": 10,"foo.bar":"dotstring","{foobar}":"bracestring","[foobar]":"bracket string", "foo:bar":"colonstring", "empty1":"", "empty2":{}}'
  kind: ConfigMap
  metadata:
    name: generate-log
