# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
  actions.yaml: |
    # ---
    # Remember, leave a key empty if there is no value.  None will be a string,
    # not a Python "NoneType"
    #
    # Also remember that all examples have 'disable_action' set to True.  If you
    # want to use this action as a template, be sure to set this to False after
    # copying it.

    actions:
      1:
        action: delete_indices
        description: >-
          Delete .operations indices older than 30 days.
          Ignore the error if the filter does not
          result in an actionable list of indices (ignore_empty_list).
          See https://www.elastic.co/guide/en/elasticsearch/client/curator/5.2/ex_delete_indices.html
        options:
          ignore_empty_list: True
          timeout_override: 300
          continue_if_exception: False
          disable_action: False
        filters:
        - filtertype: pattern
          kind: regex
          value: '^\.operations\..*$'
          exclude: False
        - filtertype: age
          source: name
          direction: older
          timestring: '%Y.%m.%d'
          unit: days
          unit_count: 7
          exclude: False
      2:
        action: delete_indices
        description: >-
          Delete .operations indices older than 30 days.
          Ignore the error if the filter does not
          result in an actionable list of indices (ignore_empty_list).
          See https://www.elastic.co/guide/en/elasticsearch/client/curator/5.2/ex_delete_indices.html
        options:
          ignore_empty_list: True
          timeout_override: 300
          continue_if_exception: False
          disable_action: False
        filters:
        - filtertype: pattern
          kind: regex
          value: '^project\.myapp\..*$'
          exclude: False
        - filtertype: age
          source: name
          direction: older
          timestring: '%Y.%m.%d'
          unit: days
          unit_count: 1
          exclude: False
      3:
        action: delete_indices
        description: >-
          Delete .operations indices older than 30 days.
          Ignore the error if the filter does not
          result in an actionable list of indices (ignore_empty_list).
          See https://www.elastic.co/guide/en/elasticsearch/client/curator/5.2/ex_delete_indices.html
        options:
          ignore_empty_list: True
          timeout_override: 300
          continue_if_exception: False
          disable_action: False
        filters:
        - filtertype: pattern
          kind: regex
          value: '.*prod.*\..*$'
          exclude: False
        - filtertype: age
          source: name
          direction: older
          timestring: '%Y.%m.%d'
          unit: months
          unit_count: 1
          exclude: False
      4:
        action: delete_indices
        description: >-
          Delete .operations indices older than 30 days.
          Ignore the error if the filter does not
          result in an actionable list of indices (ignore_empty_list).
          See https://www.elastic.co/guide/en/elasticsearch/client/curator/5.2/ex_delete_indices.html
        options:
          ignore_empty_list: True
          timeout_override: 300
          continue_if_exception: False
          disable_action: False
        filters:
        - filtertype: pattern
          kind: regex
          value: '^project\..+\-dev.*\..*$'
          exclude: False
        - filtertype: age
          source: name
          direction: older
          timestring: '%Y.%m.%d'
          unit: days
          unit_count: 31
          exclude: False
      5:
        action: delete_indices
        description: >-
          Delete .operations indices older than 30 days.
          Ignore the error if the filter does not
          result in an actionable list of indices (ignore_empty_list).
          See https://www.elastic.co/guide/en/elasticsearch/client/curator/5.2/ex_delete_indices.html
        options:
          ignore_empty_list: True
          timeout_override: 300
          continue_if_exception: False
          disable_action: False
        filters:
        - filtertype: pattern
          kind: regex
          value: '^project\.myapp\-dev\..*$|^\.operations\..*$|.*prod.*\..*$|^project\..+\-dev.*\..*$|^\.searchguard\..*$|^\.kibana.*$'
          exclude: False
        - filtertype: age
          source: name
          direction: older
          timestring: '%Y.%m.%d'
          unit: days
          unit_count: 7
          exclude: False

  config.yaml: |
    # Logging example curator config file

    # uncomment and use this to override the defaults from env vars
    #.defaults:
    #  delete:
    #    days: 30
    #  runhour: 0
    #  runminute: 0

    # to keep ops logs for a different duration:
    #.operations:
    #  delete:
    #    weeks: 8

    # example for a normal project
    #myapp:
    #  delete:
    #    weeks: 1
  curator5.yaml: "---\nclient:\n  hosts:\n  - ${ES_HOST}\n  port: ${ES_PORT}\n  use_ssl:
    True\n  certificate: ${ES_CA}\n  client_cert: ${ES_CLIENT_CERT}\n  client_key:
    ${ES_CLIENT_KEY}\n  ssl_no_validate: False\n  timeout: ${CURATOR_TIMEOUT}\n  master_only:
    False\nlogging:\n  loglevel: ${CURATOR_LOG_LEVEL}\n  logformat: default\n  blacklist:
    ['elasticsearch', 'urllib3'] \n  "
